<?php
return [
  'animals'   => [
    'label'           => 'Bird',
    'route'           => 'admin.animals',
    'thumbnail_field' => 'thumbnail_url',
    'subtitle_field'  => 'scientific_name',
    'title_field'     => 'common_name',
    'thumb_wrapper'   => 'w-20 h-20',
    'thumb_ratio'     =>  null,
   ],
  'locations' => [
    'label'             => 'Location',
    'route'             => 'admin.locations',
    'thumbnail_field'   => 'image',
    'subtitle_field'    => 'city',
    'title_field'       => 'name',
    'thumb_wrapper'     => 'w-40 h-24',
    'thumb_ratio'       =>  null,
    ],
  'media' => [
    'label'             => 'Media',
    'route'             => 'admin.media',
    'thumbnail_field'   => 'thumbnail_url',
    'subtitle_field'    => 'subtitle',
    'title_field'       => 'title', 
    'thumb_wrapper'     => 'w-40 h-24',
    'thumb_ratio'       =>  null,
    ],
  'orders' => [
    'label'             => 'Order',
    'route'             => 'admin.orders',
    'thumbnail_field'   =>  null,
    'subtitle_field'    =>  null,
    'title_field'       => 'title', 
    'thumb_wrapper'     =>  null,
    'thumb_ratio'       =>  null,
    ],
  'families' => [
    'label'             => 'Family',
    'route'             => 'admin.families',
    'thumbnail_field'   =>  null,
    'subtitle_field'    => 'subtitle',
    'title_field'       => 'title', 
    'thumb_wrapper'     =>  null,
    'thumb_ratio'       =>  null,
    ],    
  'genera' => [
    'label'             => 'Genus',
    'route'             => 'admin.genera',
    'thumbnail_field'   =>  null,
    'subtitle_field'    => 'subtitle',
    'title_field'       => 'title', 
    'thumb_wrapper'     =>  null,
    'thumb_ratio'       =>  null,
    ],
];
